#!/usr/bin/env zsh

if [[ "$1" == 'linux' ]]; then
  [[ "${OSTYPE}" == "linux-gnu" ]] && return 0 || return 1
fi

if [[ "$1" == 'bsd' ]]; then
  [[ "$(uname)" == *"BSD"* ]] && return 0 || return 1
fi

if [[ "$1" == 'macos' ]]; then
  [[ "$(uname)" == "Darwin"* ]] && return 0 || return 1
fi

if [[ "$1" == 'android' ]]; then
  [[ "${OSTYPE}" == "linux-android"* ]] && return 0 || return 1
fi

if [[ "$1" == 'termux' ]]; then
  [[ "${OSTYPE}" == "linux-android"* ]] && return 0 || return 1
fi

if [[ "$1" == 'ssh' ]]; then
  [[ -n "$SSH_CONNECTION" ]] && return 0 || return 1
fi

if [[ "$1" == 'vte' ]]; then
  [ "${VTE_VERSION:-0}" -ge 3405 ] && return 0 || return 1
fi

if [[ "$1" == 'openwrt' ]]; then
  [[ "$+commands[opkg]" == "1" ]] && return 0 || return 1
fi

return 1
