#!/usr/bin/env zsh

is-recursive-function exist() {
  local r_dir="$PWD"

  if [[ -e "$r_dir/$1" ]]; then
    return 0
  fi

  while [[ "$r_dir" != "/" ]]; do
    r_dir="${r_dir:h}"
    if [[ -e "$r_dir/$1" ]]; then
      return 0
    fi
  done

  return -1
}
